import type { Patient } from '../types/Patient';
import type { Appointment, TimeSlot } from '../types/Appointment';
import type { QueueEntry } from '../types/QueueEntry';

// Mock Patients
export const mockPatients: Patient[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    dateOfBirth: '1985-03-15',
    phone: '555-0101',
    email: 'john.doe@email.com',
    address: '123 Main St, Cityville',
    emergencyContact: '555-0100',
    registrationDate: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    dateOfBirth: '1990-07-22',
    phone: '555-0102',
    email: 'jane.smith@email.com',
    address: '456 Oak Ave, Townsville',
    emergencyContact: '555-0100',
    registrationDate: '2024-02-20T14:30:00Z',
  },
  {
    id: 3,
    firstName: 'Robert',
    lastName: 'Johnson',
    dateOfBirth: '1978-11-03',
    phone: '555-0103',
    email: 'robert.j@email.com',
    address: '789 Pine Rd, Villagetown',
    emergencyContact: '555-0100',
    registrationDate: '2024-03-10T09:15:00Z',
  },
  {
    id: 4,
    firstName: 'Maria',
    lastName: 'Garcia',
    dateOfBirth: '1995-05-18',
    phone: '555-0104',
    email: 'maria.g@email.com',
    address: '321 Elm St, Metro City',
    emergencyContact: '555-0100',
    registrationDate: '2024-04-05T11:00:00Z',
  },
  {
    id: 5,
    firstName: 'David',
    lastName: 'Wilson',
    dateOfBirth: '1982-12-30',
    phone: '555-0105',
    email: 'david.w@email.com',
    address: '654 Birch Ln, Suburbia',
    emergencyContact: '555-0100',
    registrationDate: '2024-05-12T16:20:00Z',
  },
];

// Mock Time Slots
export const mockTimeSlots: TimeSlot[] = [
  { id: 1, slotTime: '09:00' },
  { id: 2, slotTime: '09:30' },
  { id: 3, slotTime: '10:00' },
  { id: 4, slotTime: '10:30' },
  { id: 5, slotTime: '11:00' },
  { id: 6, slotTime: '11:30' },
  { id: 7, slotTime: '12:00' },
  { id: 8, slotTime: '12:30' },
  { id: 9, slotTime: '13:00' },
  { id: 10, slotTime: '13:30' },
  { id: 11, slotTime: '14:00' },
  { id: 12, slotTime: '14:30' },
  { id: 13, slotTime: '15:00' },
  { id: 14, slotTime: '15:30' },
  { id: 15, slotTime: '16:00' },
  { id: 16, slotTime: '16:30' },
];

// Mock Appointments (mutable for updates)
export let mockAppointments: Appointment[] = [
  {
    id: 1,
    patientId: 1,
    doctorId: 2,
    patientName: 'John Doe',
    doctorName: 'Dr. Sarah Smith',
    appointmentDate: new Date().toISOString().split('T')[0],
    startTime: '10:00',
    endTime: '10:30',
    status: 'SCHEDULED',
    medicalNotes: 'Initial consultation',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    patientId: 2,
    doctorId: 2,
    patientName: 'Jane Smith',
    doctorName: 'Dr. Sarah Smith',
    appointmentDate: new Date().toISOString().split('T')[0],
    startTime: '11:00',
    endTime: '11:30',
    status: 'SCHEDULED',
    medicalNotes: 'Follow-up on blood work',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    patientId: 3,
    doctorId: 3,
    patientName: 'Robert Johnson',
    doctorName: 'Dr. Michael Johnson',
    appointmentDate: new Date().toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '14:30',
    status: 'SCHEDULED',
    medicalNotes: 'Neurology consultation',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    patientId: 4,
    doctorId: 2,
    patientName: 'Maria Garcia',
    doctorName: 'Dr. Sarah Smith',
    appointmentDate: new Date().toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '14:30',
    status: 'SCHEDULED',
    medicalNotes: 'Headache and dizziness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    patientId: 5,
    doctorId: 2,
    patientName: 'David Wilson',
    doctorName: 'Dr. Sarah Smith',
    appointmentDate: new Date().toISOString().split('T')[0],
    startTime: '15:30',
    endTime: '16:00',
    status: 'SCHEDULED',
    medicalNotes: 'Follow-up on blood pressure',
    createdAt: new Date().toISOString(),
  },
];

// Mock Queue Entries (mutable for updates)
export let mockQueueEntries: QueueEntry[] = [
  {
    id: 1,
    patientId: 1,
    patientName: 'John Doe',
    doctorId: 2,
    doctorName: 'Dr. Sarah Smith',
    priorityLevel: 'NORMAL',
    status: 'WAITING',
    position: 1,
    enteredAt: new Date(Date.now() - 25 * 60000).toISOString(), // 25 mins ago
    notes: '',
  },
  {
    id: 2,
    patientId: 2,
    patientName: 'Jane Smith',
    doctorId: 2,
    doctorName: 'Dr. Sarah Smith',
    priorityLevel: 'URGENT',
    status: 'WAITING',
    position: 2,
    enteredAt: new Date(Date.now() - 15 * 60000).toISOString(), // 15 mins ago
    notes: 'High fever reported',
  },
  {
    id: 3,
    patientId: 4,
    patientName: 'Maria Garcia',
    doctorId: 2,
    doctorName: 'Dr. Sarah Smith',
    priorityLevel: 'NORMAL',
    status: 'WAITING',
    position: 3,
    enteredAt: new Date(Date.now() - 5 * 60000).toISOString(), // 5 mins ago
    notes: '',
  },
  {
    id: 4,
    patientId: 3,
    patientName: 'Robert Johnson',
    doctorId: 3,
    doctorName: 'Dr. Michael Johnson',
    priorityLevel: 'EMERGENCY',
    status: 'WAITING',
    position: 1,
    enteredAt: new Date(Date.now() - 10 * 60000).toISOString(), // 10 mins ago
    notes: 'Chest pain, possible cardiac issue',
  },
  {
    id: 5,
    patientId: 5,
    patientName: 'David Wilson',
    doctorId: 3,
    doctorName: 'Dr. Michael Johnson',
    priorityLevel: 'NORMAL',
    status: 'WAITING',
    position: 2,
    enteredAt: new Date(Date.now() - 2 * 60000).toISOString(), // 2 mins ago
    notes: 'Regular checkup',
  },
];